//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCorePal.Toolkit.Pinyins.ChineseName.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCorePal.Toolkit.Pinyins.ChineseName.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 赵	zhào
        ///钱	qián
        ///孙	sūn
        ///李	lǐ
        ///周	zhōu
        ///吴	wú
        ///郑	zhèng
        ///王	wáng
        ///冯	féng
        ///陈	chén
        ///褚	chǔ
        ///卫	wèi
        ///蒋	jiǎng
        ///沈	shěn
        ///韩	hán
        ///杨	yáng
        ///朱	zhū
        ///秦	qín
        ///尤	yóu
        ///许	xǔ
        ///何	hé
        ///吕	lǚ
        ///施	shī
        ///张	zhāng
        ///孔	kǒng
        ///曹	cáo
        ///严	yán
        ///华	huà
        ///金	jīn
        ///魏	wèi
        ///陶	táo
        ///姜	jiāng
        ///戚	qī
        ///谢	xiè
        ///邹	zōu
        ///喻	yù
        ///柏	bǎi
        ///水	shuǐ
        ///窦	dòu
        ///章	zhāng
        ///云	yún
        ///苏	sū
        ///潘	pān
        ///葛	gě
        ///奚	xī
        ///范	fàn
        ///彭	péng
        ///郎	láng
        ///鲁	lǔ
        ///韦	wéi
        ///昌	chāng
        ///马	mǎ
        ///苗	miáo
        ///凤	fèng
        ///花	huā
        ///方	fāng
        ///俞	yú
        ///任	rèn
        ///袁	yuán
        ///柳	liǔ
        ///酆	fēng
        ///鲍	bào
        ///史	shǐ
        ///唐	táng
        ///费	fèi
        ///廉	lián
        ///岑	cén
        ///薛	xuē
        ///雷	léi
        ///贺	hè
        ///倪	ní
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ChineseNames {
            get {
                return ResourceManager.GetString("ChineseNames", resourceCulture);
            }
        }
    }
}
